--- 
- name: sample Playbook
  hosts: Slave2
  remote_user: ubuntu
  become: true
  tasks:
    - name: install tomcat
      yum: 
        name: apache2
        state: absent
    - name: "run httpd"
      service:
        name: apache2
        state: stopped
    - name: create a content
      copy:
        content: "congratulations for your first playbook"
        dest: /var/www/html/index.html
