---
- name: create a user
  hosts: Slave2
  become: true
  vars_files:
    - secret.yml
  tasks:
    - name: creating a user
      user: 
        name: "{{ username }}"
        password: "{{ pwhash }}"
...        