---
- name: install tomcat server
  hosts: Slave2
  become: true
  vars:
    - tomcat_url: https://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.66/bin/apache-tomcat-8.5.66.tar.gz
    - tomcat_package: apache-tomcat-8.5.66
  
  tasks:
  - name: install java
    yum :
      name: default-jre
      state: latest

  - name: download tomcat server packages
    get_url:
      url: "{{ tomcat_url}}"
      dest: /usr/local

  - name: extract tomcat packages
    unarchive:
      src: /usr/local/{{ tomcat_package }}.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: start tomcat services
    shell: nohup /usr/local/{{ tomcat_package }}/bin/startup.sh